### ISSUE TITLE
Add code formatter

### ISSUE THREAD

**Issue by josdem** [josdem/spring-web-resource-client#2]
As **a user**, I want to have a code formatted **so that** I can format the code before pushing it to the repository.

**Acceptance Criteria**

- I am able to run code formatted from the command line
- I am able to integrate it with Gradle

**References**
- https://plugins.gradle.org/plugin/com.diffplug.spotless
- https://github.com/josdem/spring-boot-authorization-server/blob/main/build.gradle

**Comment by RobinKumar5986** [comment]
I would like to work on this but exactly which code you want to be formatted

**Comment by josdem** [comment]
Hi @RobinKumar5986 , your collaboration is appreciated! Please take a look at the references link; there you will find the formatter and the Java code we would like to format. Let me know if any questions.
